spring:
  data:
    jpa:
      repositories:
      enabled: "true"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: "update"
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}"
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob.non_contextual_creation: "true"

  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/cms}"
    username: "${SPRING_DATASOURCE_USERNAME:admin}"
    password: "${SPRING_DATASOURCE_PASSWORD:zaq1ZAQ!}"